### ISSUE TITLE
[Trinket] Brown Eye

### ISSUE THREAD

**Issue by FacemanFoothand** [FacemanFoothand/AlphaTeam#4]
When held it makes poops slowly shoot at enemies in the room.

"I got eye in my poop!"

Assets:
![trinket_browneye](https://cloud.githubusercontent.com/assets/24993635/21793505/4745e286-d6af-11e6-94ed-e6621df7e791.png)

Sprite: Completed
![dirteye_trinket_large](https://cloud.githubusercontent.com/assets/24993635/21794133/c56a3536-d6b4-11e6-8dce-272ff21727ea.png)

Code: Complete 

File: Merged

**Comment by FacemanFoothand** [comment]
Native Abearican was unable to figure out the entire code for this item. If you know how it can work let him know!

**Comment by jtmcginnis** [comment]
The current issue appears to be that the game is not recognising ENTITY_POOP as a proper EntityType.

**Comment by mikemedina** [comment]
@jtmcginnis Can you push a branch with the code you have so far so others can take a look?

**Comment by jtmcginnis** [comment]
@mikemedina I will as soon as I get the chance today

**Comment by jtmcginnis** [comment]
@mikemedina Issue was resolved, I'll remove the needs help tag

**Comment by FacemanFoothand** [comment]
Testing Notes: Randomize (and possibly stagger) tears from poop? I know the randomization is possible, but is it also possible to stagger when each individual poop shoots?
@jtmcginnis

**Comment by jtmcginnis** [comment]
@FacemanFoothand I have class until 2. I'll test it out then. LUA has weird ways of random number generation, but I think it's possible. I have a question for you, too! Do you think it should synergise with brimstone, technology, etc...? I tested it with those items in place and, frankly, even at incredibly slow fire rates, it was far too powerful, because of the infinite range.

**Comment by FacemanFoothand** [comment]
@jtmcginnis I don't think so. We will just stick to normal tears! And sounds good, let me know if you make any progress. If not, don't stress too much over it and move on to another issue available!

**Comment by mikemedina** [comment]
I would like to see tear "effects" incorporated:

Homing Tears
Poison Tears
Charm Tears
Fear Tears
Confusion Tears
Slowing Tears

**Comment by jtmcginnis** [comment]
@mikemedina It will work with all tear effects. Cricket's body, homing, poison, you name it. I did not allow for it to work with Brimstone or Tech because the infinite range made the item too OP. I tried out Ludovico, but it was pretty underwhelming haha. The poop would break and the tear would float there doing nothing, so I left Ludovico out. Also, mom's knife just cannot work since the player:FireKnife() function needs an Entity and Poop is not an entity. It's a grid entity which, for some reason, is not an extension of the Entity type.
